### ISSUE TITLE
Range error websocket

### ISSUE THREAD

**Issue by Marc-Emmanuel** [Webstrates/Webstrates#12]
There might be a periodical server-side error regarding websocket and buffers. Sometimes the receiver throw the following error, crashing the server:

````
/node_modules/ws/lib/Receiver.js:317
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (webstrates/node_modules/ws/lib/Receiver.js:317:24)
    at Receiver.add (webstrate/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (webstrate/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

It might be a native BufferUtils problem. The server is currently running on a x64, debian 8 server

**Comment by kbadk** [comment]
What version of NodeJS are you running? Node 6.3? If so, could you try downgrading to 6.2?

**Comment by Marc-Emmanuel** [comment]
I am currently running the last release: node 6.8

**Comment by kbadk** [comment]
Can you try downgrading to 6.2?

**Comment by Marc-Emmanuel** [comment]
Done, I will let the server up for a while and check if this is solving the issue! Thanks Kba

**Comment by kbadk** [comment]
When I encountered similar issues, downgrading solved it me. See https://github.com/websockets/ws/issues/778.
