### ISSUE TITLE
Publisher undefined when URL prototyping from another webstrate (that has assets)

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#73]
Prototyping from another webstrate (that has assets) using `prototypeUrl` hangs and the server repeatedly logs the same error message (see below).

Reproduce:

1. Checkout latest master branch
2. Run server
3. http://localhost:7007/new?prototypeUrl=https://web:strate@webstrates.cs.au.dk/has-asset/?dl
4. Check server log in console

Error message:
```
[ERROR] process.on (/Users/raedle/Projects/Webstrates/server/webstrates.js:26:10) Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'publisher' of undefined
    at Object.module.exports.announceNewAsset (/Users/raedle/Projects/Webstrates/server/helpers/ClientManager.js:489:10)
    at /Users/raedle/Projects/Webstrates/server/helpers/AssetManager.js:362:19
    at /Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/collection.js:535:5
    at /Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/collection.js:713:5
    at handleCallback (/Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/utils.js:120:56)
    at executeCommands (/Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/bulk/ordered.js:398:12)
    at resultHandler (/Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/bulk/ordered.js:425:5)
    at /Users/raedle/Projects/Webstrates/server/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) } reason: TypeError: Cannot read property 'publisher' of undefined
    at Object.module.exports.announceNewAsset (/Users/raedle/Projects/Webstrates/server/helpers/ClientManager.js:489:10)
    at /Users/raedle/Projects/Webstrates/server/helpers/AssetManager.js:362:19
    at /Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/collection.js:535:5
    at /Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/collection.js:713:5
    at handleCallback (/Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/utils.js:120:56)
    at executeCommands (/Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/bulk/ordered.js:398:12)
    at resultHandler (/Users/raedle/Projects/Webstrates/server/node_modules/mongodb/lib/bulk/ordered.js:425:5)
    at /Users/raedle/Projects/Webstrates/server/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by raedle** [comment]
Bug introduced with commit 3a56b644366cfc519be558469278fac1d986c429
