### ISSUE TITLE
Issues with creating MongoDB server 

### ISSUE THREAD

**Issue by AdrisKhan** [Webstrates/Webstrates#89]
i cannot seem get webstbrates to successfully start, any help would be appreciated : 
here is my log!

    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Webstrates@1.6.0 start: `npm run build && node webstrates.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Webstrates@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adris/.npm/_logs/2019-02-04T12_42_36_989Z-debug.log
Adriss-MacBook-Pro:WEBSTRATES adris$ clear

Adriss-MacBook-Pro:WEBSTRATES adris$ npm install --production

> ws@0.4.32 install /Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm WARN Webstrates@1.6.0 No repository field.

added 6 packages from 10 contributors, removed 1 package, updated 3 packages and audited 8461 packages in 9.476s
found 14 vulnerabilities (6 low, 5 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Adriss-MacBook-Pro:WEBSTRATES adris$ npm run build

> Webstrates@1.6.0 build /Users/adris/Desktop/DISSERTATION/WEBSTRATES
> NODE_ENV='production' webpack -p

Hash: 8ebd7d1d0155724f2469
Version: webpack 2.7.0
Time: 2734ms
        Asset    Size  Chunks                    Chunk Names
webstrates.js  466 kB       0  [emitted]  [big]  main
   [0] ./client/webstrates/coreUtils.js 14.2 kB {0} [built]
   [1] ./client/webstrates/coreEvents.js 4.53 kB {0} [built]
   [3] ./client/webstrates/coreWebsocket.js 7.9 kB {0} [built]
   [4] ./client/config.js 1.22 kB {0} [built]
   [5] ./~/timers-browserify/main.js 1.92 kB {0} [built]
   [6] ./client/webstrates/coreDOM.js 4.63 kB {0} [built]
   [7] ./client/webstrates/coreDatabase.js 7.16 kB {0} [built]
  [12] ./client/webstrates/userObject.js 4.85 kB {0} [built]
  [13] ./client/webstrates/coreMutation.js 6.32 kB {0} [built]
  [14] ./client/webstrates/coreOpCreator.js 20.7 kB {0} [built]
  [15] ./client/webstrates/corePopulator.js 2.23 kB {0} [built]
  [19] ./client/webstrates/coreOpApplier.js 27.6 kB {0} [built]
  [30] ./client/webstrates/databaseErrors.js 1.42 kB {0} [optional] [built]
  [46] ./client/webstrates ^\.\/.*$ 1.43 kB {0} [built]
  [47] ./client/index.js 1.82 kB {0} [built]
    + 45 hidden modules
Adriss-MacBook-Pro:WEBSTRATES adris$ npm start

> Webstrates@1.6.0 start /Users/adris/Desktop/DISSERTATION/WEBSTRATES
> npm run build && node webstrates.js

> Webstrates@1.6.0 build /Users/adris/Desktop/DISSERTATION/WEBSTRATES
> NODE_ENV='production' webpack -p

Hash: 8ebd7d1d0155724f2469
Version: webpack 2.7.0
Time: 2508ms
        Asset    Size  Chunks                    Chunk Names
webstrates.js  466 kB       0  [emitted]  [big]  main
   [0] ./client/webstrates/coreUtils.js 14.2 kB {0} [built]
   [1] ./client/webstrates/coreEvents.js 4.53 kB {0} [built]
   [3] ./client/webstrates/coreWebsocket.js 7.9 kB {0} [built]
   [4] ./client/config.js 1.22 kB {0} [built]
   [5] ./~/timers-browserify/main.js 1.92 kB {0} [built]
   [6] ./client/webstrates/coreDOM.js 4.63 kB {0} [built]
   [7] ./client/webstrates/coreDatabase.js 7.16 kB {0} [built]
  [12] ./client/webstrates/userObject.js 4.85 kB {0} [built]
  [13] ./client/webstrates/coreMutation.js 6.32 kB {0} [built]
  [14] ./client/webstrates/coreOpCreator.js 20.7 kB {0} [built]
  [15] ./client/webstrates/corePopulator.js 2.23 kB {0} [built]
  [19] ./client/webstrates/coreOpApplier.js 27.6 kB {0} [built]
  [30] ./client/webstrates/databaseErrors.js 1.42 kB {0} [optional] [built]
  [46] ./client/webstrates ^\.\/.*$ 1.43 kB {0} [built]
  [47] ./client/index.js 1.82 kB {0} [built]
    + 45 hidden modules
[12:45:24] [WARN]   Backend._shimDocAction (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/sharedb/lib/backend.js:92:13) DEPRECATED: "doc" middleware action. Use "readSnapshots" instead. Pass `disableDocAction: true` option to ShareDB to disable the "doc" action and this warning.
[12:45:24] [WARN]   Backend._shimAfterSubmit (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/sharedb/lib/backend.js:109:13) DEPRECATED: "after submit" middleware action. Use "afterSubmit" instead. Pass `disableSpaceDelimitedActions: true` option to ShareDB to disable the "after submit" action and this warning.
[12:45:24] [LOG]    Object.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/webstrates.js:273:10) Listening on http://localhost:7007/ in 1 thread(s)

/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Webstrates@1.6.0 start: `npm run build && node webstrates.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Webstrates@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adris/.npm/_logs/2019-02-04T12_45_24_501Z-debug.log
Adriss-MacBook-Pro:WEBSTRATES adris$

**Comment by kbadk** [comment]
Have you installed MongoDB?

**Comment by AdrisKhan** [comment]
yes, i am currently double checking but i am somewhat sure i have
On 4 Feb 2019, at 12:49, Kristian Antonsen <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you installed MongoDB?

**Comment by AdrisKhan** [comment]
yes, i am currently running the latest version as such: 

Last login: Mon Feb  4 12:31:06 on ttys000
Adriss-MacBook-Pro:~ adris$ cd ~/Desktop/Python
-bash: cd: /Users/adris/Desktop/Python: No such file or directory
Adriss-MacBook-Pro:~ adris$ node -v
v11.9.0
Adriss-MacBook-Pro:~ adris$ cd /Users/adris/Desktop/DISSERTATION/WEBSTRATES 
Adriss-MacBook-Pro:WEBSTRATES adris$ npm

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/adris/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.5.0 /usr/local/lib/node_modules/npm
Adriss-MacBook-Pro:WEBSTRATES adris$ npm install --production 
npm WARN Webstrates@1.6.0 No repository field.

audited 8461 packages in 6.57s
found 14 vulnerabilities (6 low, 5 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Adriss-MacBook-Pro:WEBSTRATES adris$ npm run build

> Webstrates@1.6.0 build /Users/adris/Desktop/DISSERTATION/WEBSTRATES
> NODE_ENV='production' webpack -p

Hash: a4d3efb79ad9198cc088
Version: webpack 2.7.0
Time: 2718ms
        Asset    Size  Chunks                    Chunk Names
webstrates.js  466 kB       0  [emitted]  [big]  main
   [0] ./client/webstrates/coreUtils.js 14.2 kB {0} [built]
   [1] ./client/webstrates/coreEvents.js 4.53 kB {0} [built]
   [2] ./client/webstrates/globalObject.js 5.25 kB {0} [built]
   [3] ./client/webstrates/coreWebsocket.js 7.9 kB {0} [built]
   [4] ./client/config.js 1.22 kB {0} [built]
   [5] ./~/timers-browserify/main.js 1.92 kB {0} [built]
   [6] ./client/webstrates/coreDOM.js 4.63 kB {0} [built]
   [7] ./client/webstrates/coreDatabase.js 7.16 kB {0} [built]
   [8] ./client/webstrates/corePathTree.js 10.1 kB {0} [built]
  [13] ./client/webstrates/coreMutation.js 6.32 kB {0} [built]
  [14] ./client/webstrates/coreOpCreator.js 20.7 kB {0} [built]
  [15] ./client/webstrates/corePopulator.js 2.23 kB {0} [built]
  [19] ./client/webstrates/coreOpApplier.js 27.6 kB {0} [built]
  [46] ./client/webstrates ^\.\/.*$ 1.43 kB {0} [built]
  [47] ./client/index.js 1.82 kB {0} [built]
    + 45 hidden modules
Adriss-MacBook-Pro:WEBSTRATES adris$ npm start

> Webstrates@1.6.0 start /Users/adris/Desktop/DISSERTATION/WEBSTRATES
> npm run build && node webstrates.js


> Webstrates@1.6.0 build /Users/adris/Desktop/DISSERTATION/WEBSTRATES
> NODE_ENV='production' webpack -p

Hash: a4d3efb79ad9198cc088
Version: webpack 2.7.0
Time: 2586ms
        Asset    Size  Chunks                    Chunk Names
webstrates.js  466 kB       0  [emitted]  [big]  main
   [0] ./client/webstrates/coreUtils.js 14.2 kB {0} [built]
   [1] ./client/webstrates/coreEvents.js 4.53 kB {0} [built]
   [2] ./client/webstrates/globalObject.js 5.25 kB {0} [built]
   [3] ./client/webstrates/coreWebsocket.js 7.9 kB {0} [built]
   [4] ./client/config.js 1.22 kB {0} [built]
   [5] ./~/timers-browserify/main.js 1.92 kB {0} [built]
   [6] ./client/webstrates/coreDOM.js 4.63 kB {0} [built]
   [7] ./client/webstrates/coreDatabase.js 7.16 kB {0} [built]
   [8] ./client/webstrates/corePathTree.js 10.1 kB {0} [built]
  [13] ./client/webstrates/coreMutation.js 6.32 kB {0} [built]
  [14] ./client/webstrates/coreOpCreator.js 20.7 kB {0} [built]
  [15] ./client/webstrates/corePopulator.js 2.23 kB {0} [built]
  [19] ./client/webstrates/coreOpApplier.js 27.6 kB {0} [built]
  [46] ./client/webstrates ^\.\/.*$ 1.43 kB {0} [built]
  [47] ./client/index.js 1.82 kB {0} [built]
    + 45 hidden modules
[12:52:52] [WARN]   Backend._shimDocAction (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/sharedb/lib/backend.js:92:13) DEPRECATED: "doc" middleware action. Use "readSnapshots" instead. Pass `disableDocAction: true` option to ShareDB to disable the "doc" action and this warning.
[12:52:52] [WARN]   Backend._shimAfterSubmit (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/sharedb/lib/backend.js:109:13) DEPRECATED: "after submit" middleware action. Use "afterSubmit" instead. Pass `disableSpaceDelimitedActions: true` option to ShareDB to disable the "after submit" action and this warning.
[12:52:52] [LOG]    Object.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/webstrates.js:273:10) Listening on http://localhost:7007/ in 1 thread(s)

/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:197:13)
    at Connection.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:285:13)
    at Connection.emit (events.js:197:13)
    at Socket.<anonymous> (/Users/adris/Desktop/DISSERTATION/WEBSTRATES/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Webstrates@1.6.0 start: `npm run build && node webstrates.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Webstrates@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adris/.npm/_logs/2019-02-04T12_52_52_919Z-debug.log
Adriss-MacBook-Pro:WEBSTRATES adris$

**Comment by kbadk** [comment]
MongoDB does not appear to be running on your machine.

**Comment by AdrisKhan** [comment]
correct
On 4 Feb 2019, at 13:04, Kristian Antonsen <notifications@github.com<mailto:notifications@github.com>> wrote:


MongoDB does not appear to be running on your machine.

**Comment by AdrisKhan** [comment]
Heya! Really appreciated. It was mongo after all !

Adris Khan
President
UCL Data Science Society
adris.khan.16@ucl.ac.uk<mailto:adris.khan.15@ucl.ac.uk>
+44 7512898758
www.uclguild.com<http://www.uclguild.com/>








This email and any attachments are confidential and are solely intended for the addressee. If you are not the named addressee you should not disseminate, distribute or copy this e-mail and you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. If you have received this e-mail by mistake, please notify the sender immediately by e-mail and delete this e-mail from your system. Replies to this email may be monitored by the UCL Guild for quality and training purposes. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the UCL Guild, University College London Union or its associated companies and societies. Where verification of this email is required, please request a hard-copy version


UCL Guild - UCL's largest and fastest growing society


On 4 Feb 2019, at 13:04, Kristian Antonsen <notifications@github.com<mailto:notifications@github.com>> wrote:


MongoDB does not appear to be running on your machine.

**Comment by kbadk** [comment]
You're welcome.
