### ISSUE TITLE
Webstrates server crashes looking for missing zipFile in uploads

### ISSUE THREAD

**Issue by eaganj** [Webstrates/Webstrates#98]
Loading certain webstrates (in this case, codestrates) causes the Webstrates server to crash with the following trace :

```
/Users/eaganj/Projects/Extern/Webstrates/helpers/HttpRequestController.js:152
		zipFile.on('entry', entry => {
		        ^

TypeError: Cannot read property 'on' of undefined
    at /Users/eaganj/Projects/Extern/Webstrates/helpers/HttpRequestController.js:152:11
    at /Users/eaganj/Projects/Extern/Webstrates/node_modules/yauzl/index.js:34:21
```

For the affected webstrates, this systematically causes the server to crash.  I added a tracing statement to `HttpRequestController.js` to reveal that the server is attempting to load a file in webstrates_root/uploads/ that does not exist.  E.g. :

```
/path/to/Webstrates/uploads/3f9b2695547b0135399acbc086545197
ls: /path/to/Webstrates/uploads/3f9b2695547b0135399acbc086545197: No such file or directory
```

I'm not sure how to provide more information about what part of the webstrate is actually triggering the load.  (I cannot `wget` the webstrate since it is access (oauth) protected.)

**Comment by kbadk** [comment]
I don't think anymore information is needed – the problem and solution seems clear. How you ended up in a scenario where the asset exists in the database, but not in the file system is odd, though.

However, I actually wrote a script to find these dangling records. This doesn't inherently fix the problem, but it'll fix this particular instance (and also give you some insight into any other dangling records you may have).

From the Webstrates root folder, you should try to run `node cleanup.js`. It's safe to run even if you're just curious – you'll be prompted before the script takes any actions.

**Comment by svnhub** [comment]
A series of commits should have now more or less indirectly fixed this issue so that at least the server doesn't crash anymore: a1bb673, e51c0a9, b192eed, 74df44f
